baseurl = "https://1122018.ca/"
canonifyurls = true
copyright = "Copyright &copy; 2018 - 1.12.2018"
enableEmoji = true
paginate = 3
pygmentsCodeFences = true
summaryLength = 30
theme = "kiera"
title = "1.12.2018"
disqusShortname = "1-12-2018"
googleAnalytics = "UA-128264380-4"
[author]
facebook = ""
github = ""
gitlab = ""
instagram = ""
linkedin = ""
name = ""
twitter = ""
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
tagline = "Today I changed my life."
